image: node:latest

default:
    tags:
        - "node:latest"

stages:
    - build
    - test

cache:
    paths:
        - node_modules/

install:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - npm run lint
        - npm run test
